version: '3.7'

services:
  scrape_colors:
    build: ./scrape_colors
    volumes:
      - ./scrape_colors:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
    tty: true

  db:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    hostname: db
    env_file:
      - ./.env

volumes:
  mysql_data:
    driver: local
